name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Backend Image
        run: docker build -t my-backend ./backend

      - name: Build Frontend Image
        run: docker build -t my-frontend ./frontend

      - name: Build Success
        run: echo "Both images built successfully!"