name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      - name: Build Backend Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/my-backend:latest ./backend

      - name: Push Backend Image
        run: docker push ghcr.io/${{ github.repository_owner }}/my-backend:latest

      - name: Build Frontend Image
        run: docker build -t ghcr.io/${{github.repository_owner}}/my-frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push ghcr.io/${{ github.repository_owner }}/my-frontend:latest

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/my-app

            echo "Pulling latest images..."
            docker compose -f docker-compose.prod.yml pull

            echo "Starting updated containers..."
            docker compose -f docker-compose.prod.yml up -d

            echo "Checking containers..."
            docker compose -f docker-compose.prod.yml ps

      - name: Build Success
        run: echo "Both images built successfully!"