name: Deploy SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTHKEY }}

    - name: Test SSH connection
      uses: appleboy/ssh-action@v1.2.2
      with:
        host:  ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd ~/my-app

          echo "Pulling latest Docker images..."
          docker compose -f docker-compose.prod.yml pull

          echo "Starting updated containers..."
          docker compose -f docker-compose.prod.yml up -d

          echo "Checking running containers..."
          docker compose -f docker-compose.prod.yml ps